# Generated by Django 3.0.5 on 2020-05-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200503_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entre',
            name='idea_title',
        ),
    ]
