# Generated by Django 3.0.5 on 2020-05-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20200503_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to='user_app.Userp'),
        ),
    ]
