# Generated by Django 3.0.5 on 2020-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20200506_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='logo',
            field=models.ImageField(default='d.jpg', upload_to='idea/logo'),
        ),
        migrations.AlterField(
            model_name='entre',
            name='logo',
            field=models.ImageField(default='d.jpg', upload_to='entre/logo'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='logo',
            field=models.ImageField(default='d.jpg', upload_to='investor/logo'),
        ),
    ]
